name: Automated Release Builder

on:
  push:
    tags:
      - "*"

jobs:
  build_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: make verify      - name: Get the tag version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Build Release
        run: ./dev/build-release.sh

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "./*"
          tag: ${{ steps.get_version.outputs.VERSION }}
          name: Release ${{ steps.get_version.outputs.VERSION }}
          allowUpdates: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
