# required secrets:
# - DOCKER_USER: docker hub username
# - DOCKER_TOKEN: docker hub access token
# - DOCKER_REPO: docker repository in the ORGANISATION/IMAGENAME format

name: Docker image

# keep it simple for now, create a new Docker image after each rebuild
on: [push]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Build
        run: |
          docker build -f docker/Dockerfile --tag ${{ secrets.DOCKER_REPO }}:latest .
      - name: Login to Docker Hub
        #        if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request' && github.repository == 'legal-i/agent-example'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Push to Docker Hub
        #        if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request' && github.repository == 'legal-i/agent-example'
        run: |
          docker push ${{ secrets.DOCKER_REPO }}:latest
