# required secrets:
# - LEGALI_API_URL:
# - LEGALI_CLIENT_SECRET:
# - DOCKER_REPO: docker repository in the ORGANISATION/IMAGENAME format

name: Test Agent Example

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Person to greet"
        required: true
        default: "Mona the Octocat"

jobs:
  test-agent:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Start & Validate Agent
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ secrets.DOCKER_REPO }}:latest
          options: -e LEGALI_API_URL=${{ secrets.LEGALI_API_URL }} -e LEGALI_CLIENT_SECRET=${{ secrets.LEGALI_CLIENT_SECRET }}
          run: |
            echo "# START AGENT"
            env
            nohup java -XX:MaxRAMPercentage=90.0 org.springframework.boot.loader.JarLauncher > /tmp/tmp.log 2>&1 &
            sleep 120
            pkill -e java
            echo "DONE - Looking for 'LegalCase has successfully been deleted' in log file..."
            cat /tmp/tmp.log
            if  grep -q "LegalCase has successfully been deleted" "/tmp/tmp.log" ; then
              exit 0;
            else
              exit 1;
            fi
