# required secrets:
# - LEGALI_API_URL:
# - LEGALI_CLIENT_SECRET:
# - DOCKER_REPO: docker repository in the ORGANISATION/IMAGENAME format

name: Test Agent Example

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Person to greet"
        required: true
        default: "Mona the Octocat"

jobs:
  test-agent:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Start Agent
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ secrets.DOCKER_REPO }}:latest
          options: -e LEGALI_API_URL=${{ secrets.LEGALI_API_URL }} -e LEGALI_CLIENT_SECRET=${{ secrets.LEGALI_CLIENT_SECRET }}
          run: |
            echo "# START AGENT"
            env
            TEMP_LOG_FILE=/tmp/tmp.log
            nohup java -XX:MaxRAMPercentage=90.0 org.springframework.boot.loader.JarLauncher &> "$TEMP_LOG_FILE" & tail -f "$TEMP_LOG_FILE" &
            sleep 20
            pkill -e java
            echo "DONE - Looking for 'LegalCase has successfully been deleted' in log file..."
            grep -q "LegalCase has successfully been deleted" $TEMP_LOG_FILE; [ $? -eq 0 ] && exit 0 || exit 1
