# required secrets:
# - LEGALI_API_URL:
# - LEGALI_CLIENT_SECRET:
# - DOCKER_REPO: docker repository in the ORGANISATION/IMAGENAME format

name: Test Agent Example

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Person to greet"
        required: true
        default: "Mona the Octocat"

jobs:
  test-agent:
    runs-on: ubuntu-latest
    steps:
      - name: I will fail
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ secrets.DOCKER_REPO }}:latest
          options: -e LEGALI_API_URL=${{ secrets.LEGALI_API_URL }} -e LEGALI_CLIENT_SECRET=${{ secrets.LEGALI_CLIENT_SECRET }}
          run: |
            exit 1;

      - name: Report Status
        if: always()
        uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}

